/** Offisielle Kosttest.no brand-assets (public/brand/ og rot-faviconer). */
export const brand = {
  logoLight: '/brand/logo-light.png',
  logoDark: '/brand/logo-dark.png',
  iconLight: '/brand/icon-light.png',
  /** App-ikon med mørk bakgrunn (PWA / deling). Favicon genereres fra iconLight. */
  appIcon: '/brand/app-icon.png',
  openGraph: '/kosttest-open-graph-1200x630.png',
  homeHeroBanner: '/brand/home-hero-banner.png',
  homeHeroBannerMobile: '/brand/home-hero-banner-mobile.png',
  homeHeroBannerCharity: '/brand/home-hero-banner-charity.png',
  homeHeroBannerCharityMobile: '/brand/home-hero-banner-charity-mobile.png',
  /** Mobilbanner for metode/transparens — brukes utenfor karusellen, ikke som egen slide. */
  homeHeroBannerMethodMobile: '/brand/home-hero-banner-independent-mobile.png',
  hubPwoDesktop: '/brand/hub-pwo-desktop.png',
  hubPwoMobile: '/brand/hub-pwo-mobile.png',
  hubPwoStimFreeDesktop: '/brand/hub-pwo-stim-free-desktop.png',
  hubPwoStimFreeMobile: '/brand/hub-pwo-stim-free-mobile.png',
  hubProteinDesktop: '/brand/hub-protein-desktop.png',
  hubProteinMobile: '/brand/hub-protein-mobile.png',
  hubProteinVeganDesktop: '/brand/hub-protein-vegan-desktop.png',
  hubProteinVeganMobile: '/brand/hub-protein-vegan-mobile.png',
  hubCreatineDesktop: '/brand/hub-kreatin-desktop.png',
  hubCreatineMobile: '/brand/hub-kreatin-mobile.png',
  hubCreatineCreapureDesktop: '/brand/hub-kreatin-creapure-desktop.png',
  hubCreatineCreapureMobile: '/brand/hub-kreatin-creapure-mobile.png',
  hubMetodeDesktop: '/brand/hub-metode-desktop.png',
  hubOmKosttestDesktop: '/brand/hub-om-kosttest-desktop.png',
  hubOmKosttestMobile: '/brand/hub-om-kosttest-mobile.png',
} as const
